version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - redis

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www  # Mounts your app directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mounts your nginx configuration
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    command: ["cron", "-f"]  # Keep the cron service running in the foreground
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: news_aggregator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
